export const ErrorCode = {
  VALIDATION: 'VALIDATION',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNSOLVABLE_LAYOUT: 'UNSOLVABLE_LAYOUT',
  INVALID_CHANGE_REQUEST: 'INVALID_CHANGE_REQUEST',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
